spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: true
    properties:
      '[hibernate.max_fetch_depth]': 3
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver        
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
  jackson:
    mapper:
      default-view-inclusion: true
server:
  port: 8080
  error:
    include-stacktrace: never
    whitelabel:
      enabled: false
    include-message: always
springdoc:
  swagger-ui:
    csrf:
      enabled: true
et-prodaja:
  storage-location: ${STORAGE_LOCATION}
jwt:
  secret: ${JWT_SECRET}
  secret2-f-a: ${JWT_SECRET_2FA}
  token-validity: ${JWT_TOKEN_VALIDITY}
  refresh-token-validity: ${JWT_REFRESH_TOKEN_VALIDITY}
  refresh-url: /api/refreshtoken
