spring:
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: validate
    open-in-view: true
  datasource:
    url: jdbc:mariadb://localhost:3306/et_prodaja
    username: ambra
server:
  port: 8080